#!/usr/bin/env bash
# Shared config + helpers for the M0 spike.
set -euo pipefail

# ---- topology ----------------------------------------------------------------
# Underlay = a fake "LAN" bridge that the netns nodes share.
BRIDGE="nbr0"
UNDERLAY_CIDR="192.168.77.0/24"
UNDERLAY_GW="192.168.77.254"

# Overlay = the Nebula network. 100.64.0.0/16 (CGNAT) so it never collides with
# k3s defaults (10.42/10.43) or a typical home LAN.
OVERLAY_CIDR="100.64.0.0/16"
NEB_PORT=4242

# nodes:  name  netns  underlay-ip  overlay-ip  am_lighthouse  groups
#   lh = lighthouse, n1/n2 = ordinary nodes (n1 in group "a", n2 in group "b")
NODES=(
  "lh  192.168.77.1   100.64.0.1   true   "
  "n1  192.168.77.11  100.64.0.11  false  a"
  "n2  192.168.77.12  100.64.0.12  false  b"
)
LIGHTHOUSE_OVERLAY="100.64.0.1"

# ---- paths -------------------------------------------------------------------
M0_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUN="${M0_DIR}/run"          # generated certs/configs/logs/pids (gitignored)
TOOLS="${M0_DIR}/tools"      # locally built tools (gitignored)
mkdir -p "$RUN" "$TOOLS"

# Prefer a locally built pkcs11-enabled nebula-cert if present.
NEBULA_CERT="$(command -v nebula-cert || true)"
[[ -x "${TOOLS}/nebula-cert" ]] && NEBULA_CERT="${TOOLS}/nebula-cert"
NEBULA_BIN="$(command -v nebula || true)"

# SoftHSM / PKCS#11 (M0.3)
SOFTHSM_TOKEN="harbor-m0-ca"
SOFTHSM_PIN="1234"
SOFTHSM_SO_PIN="5678"
CA_KEY_LABEL="harbor-ca-key"
CA_KEY_ID="01"
# common libsofthsm2 locations
for p in /usr/lib/softhsm/libsofthsm2.so /usr/lib/pkcs11/libsofthsm2.so \
         /usr/lib64/softhsm/libsofthsm2.so /usr/lib64/pkcs11/libsofthsm2.so; do
  [[ -f "$p" ]] && PKCS11_MODULE="$p" && break
done
PKCS11_MODULE="${PKCS11_MODULE:-/usr/lib/softhsm/libsofthsm2.so}"

# ---- helpers -----------------------------------------------------------------
log()  { printf '\033[1;36m[m0]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[m0]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[m0]\033[0m %s\n' "$*" >&2; exit 1; }

# write a nebula config.yml for a node into $RUN/<name>.yml
# args: name overlay_ip am_lighthouse inbound_block
write_config() {
  local name="$1" am_lh="$3" inbound="$4"
  local hosts="[]"
  [[ "$am_lh" == "false" ]] && hosts="[\"${LIGHTHOUSE_OVERLAY}\"]"
  cat > "${RUN}/${name}.yml" <<EOF
# generated by m0 spike for node: ${name}
pki:
  ca: ${RUN}/ca.crt
  cert: ${RUN}/${name}.crt
  key: ${RUN}/${name}.key
  # blocklist:           # M0.5: add a fingerprint here to test peer-side blocking
  #   - <sha256-fp>
static_host_map:
  "${LIGHTHOUSE_OVERLAY}": ["${UNDERLAY_GW%.*}.1:${NEB_PORT}"]
lighthouse:
  am_lighthouse: ${am_lh}
  interval: 60
  hosts: ${hosts}
listen:
  host: 0.0.0.0
  port: ${NEB_PORT}
punchy:
  punch: true
  respond: true
tun:
  disabled: false
  dev: nebula1
  mtu: 1300
logging:
  level: info
  format: text
firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m
  outbound:
    - port: any
      proto: any
      host: any
  inbound:
${inbound}
EOF
}

# default permissive inbound (M0.2)
INBOUND_ANY='    - port: any
      proto: any
      host: any'

# group-restricted inbound (M0.6): only members of group "a" may send ICMP
INBOUND_GROUP_A='    - port: any
      proto: icmp
      groups:
        - a'
