/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated admin principal. */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/fleet/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server-computed fleet health rollup. */
        get: operations["getFleetHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Device inventory (from heartbeats), keyset-paginated on overlay_ip. */
        get: operations["listDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit log, newest first, cursor-paginated. */
        get: operations["listAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Audit-chain integrity (in-DB scope).
         * @description "verified" = clean; "tampered" = a genuine integrity failure; a 503 means the check could not run (NOT a claim of tampering). In-DB scope only; it cannot detect tail-truncation until WORM anchoring (impl 2.13) is configured.
         */
        get: operations["verifyAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/lighthouses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The lighthouse discovery fleet. */
        get: operations["listLighthouses"];
        put?: never;
        /** Register a lighthouse. */
        post: operations["addLighthouse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The dual-control approvals inbox (all kinds). */
        get: operations["listApprovals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/approvals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A change with its sign-offs (payload included). */
        get: operations["getApproval"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/approvals/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a change as the authenticated principal (distinct-approver enforced). */
        post: operations["approveChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/approvals/{id}/deny": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deny (veto) a change as the authenticated principal. */
        post: operations["denyChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/policy/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The published fleet policy (latest committed policy.publish). */
        get: operations["getActivePolicy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/policy/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate + invariant-check a policy, then open a dual-control change. */
        post: operations["proposePolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/cloudtrust/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The published cloud-attestation trust config (latest committed cloudtrust.publish). */
        get: operations["getActiveCloudTrust"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/cloudtrust/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a cloud-trust config, then open a dual-control change. */
        post: operations["proposeCloudTrust"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/policy/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dry-run compile a draft policy for a host's groups (live analysis). */
        post: operations["compilePolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/policy/reachability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Can `from` reach `to` on proto/port under a draft policy? (A1 analysis) */
        post: operations["policyReachability"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/policy/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The all-pairs group×group reachability grid for a draft policy. (A1 analysis) */
        post: operations["policyMatrix"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/policy/tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate reachability assertions against a draft policy. (A1 analysis) */
        post: operations["policyTests"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/lighthouses/{ip}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Re-address (and re-activate) a lighthouse. */
        put: operations["replaceLighthouse"];
        post?: never;
        /** Retire a lighthouse (refuses the last active one). */
        delete: operations["removeLighthouse"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/rollouts/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current staged rollout + per-host wave status. */
        get: operations["getCurrentRollout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/rollouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a staged canary rollout. */
        post: operations["startRollout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/rollouts/current/step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Force one rollout evaluation (cron/ops). */
        post: operations["stepRollout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/rollouts/current/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abort the active rollout (touched hosts revert to prev). */
        post: operations["abortRollout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/joinkeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List join keys (secrets never returned). */
        get: operations["listJoinKeys"];
        put?: never;
        /** Create a join key; the secret is returned ONCE. */
        post: operations["createJoinKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/joinkeys/{name}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a join key by name. */
        post: operations["revokeJoinKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The enrollment approval queue (keyset-paginated on id). */
        get: operations["listEnrollments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/enrollments/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a pending enrollment (issues a cert). Requires issuance mode. */
        post: operations["approveEnrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/enrollments/{id}/deny": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a pending enrollment (no signing). */
        post: operations["denyEnrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            title: string;
            status: number;
            detail?: string;
        };
        Identity: {
            principal: string;
            roles: string[];
            /** Format: date-time */
            mfa_satisfied_at?: string;
        };
        /** @enum {string} */
        Severity: "info" | "degraded" | "critical";
        Reason: {
            code: string;
            severity: components["schemas"]["Severity"];
            count: number;
            detail: string;
            link?: string;
        };
        FleetHealth: {
            /** @enum {string} */
            status: "healthy" | "degraded" | "critical";
            reasons: components["schemas"]["Reason"][];
            totals: {
                total: number;
                expired: number;
                expiring: number;
                stale: number;
                clock_skewed: number;
                unhealthy: number;
            };
            rollout_state?: string;
            audit_ok: boolean;
        };
        Device: {
            overlay_ip: string;
            name: string;
            pilot_version?: string;
            nebula_version?: string;
            /** Format: date-time */
            cert_not_after?: string;
            applied_bundle_version: number;
            clock_offset_ms: number;
            health?: string;
            /** Format: date-time */
            last_seen?: string;
        };
        DeviceList: {
            devices: components["schemas"]["Device"][];
            /** @description page size, NOT the fleet total */
            count: number;
            /** @description cursor for the next page (present only when more rows exist) */
            next_after?: string;
        };
        AuditRow: {
            /** Format: int64 */
            seq: number;
            /** Format: date-time */
            ts: string;
            actor: string;
            action: string;
            target?: string;
            details?: string;
        };
        AuditList: {
            entries: components["schemas"]["AuditRow"][];
            count: number;
            /**
             * Format: int64
             * @description cursor for the next (older) page
             */
            next_before?: number;
        };
        AuditVerify: {
            /** @enum {string} */
            status: "verified" | "tampered";
            ok: boolean;
            /** Format: int64 */
            verified_rows: number;
            scope: string;
            detail?: string;
        };
        Lighthouse: {
            overlay_ip: string;
            hostname?: string;
            state: string;
            public_addrs: string[];
        };
        LighthouseList: {
            lighthouses: components["schemas"]["Lighthouse"][];
            count: number;
        };
        Change: {
            /** Format: int64 */
            id: number;
            kind: string;
            target?: string;
            /** @description pending | committing | committed | denied | failed */
            state: string;
            quorum: number;
            proposer: string;
            payload_sha256: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            decided_at?: string;
            /** @description the proposed content (e.g. the policy DSL); included on detail, not in lists */
            payload?: string;
        };
        Signoff: {
            actor: string;
            /** @enum {string} */
            decision: "approve" | "deny";
            /** Format: date-time */
            created_at: string;
        };
        ApprovalList: {
            approvals: components["schemas"]["Change"][];
            count: number;
        };
        ApprovalDetail: {
            change: components["schemas"]["Change"];
            signoffs: components["schemas"]["Signoff"][];
        };
        ProposeRequest: {
            /** @description the firewall policy DSL */
            policy: string;
            description?: string;
        };
        DenyRequest: {
            reason?: string;
        };
        PolicyRule: {
            from: string;
            to: string;
            proto: string;
            port: string;
        };
        ActivePolicy: {
            published: boolean;
            /** Format: int64 */
            change_id?: number;
            hash?: string;
            text?: string;
            rules?: components["schemas"]["PolicyRule"][];
        };
        CloudTrustAccount: {
            /** @description AWS account id (exact match) */
            account: string;
            /** @description allowed caller-ARN globs; empty = any ARN in the account */
            arn_patterns?: string[];
            /** @description groups granted to hosts attesting from this account */
            groups?: string[];
            /** @description issue immediately vs queue for manual approval */
            auto_issue?: boolean;
        };
        CloudTrustActive: {
            published: boolean;
            /** Format: int64 */
            change_id?: number;
            hash?: string;
            /** @description granted to every validly-attested host */
            default_groups?: string[];
            aws?: components["schemas"]["CloudTrustAccount"][];
        };
        CloudTrustProposeRequest: {
            default_groups?: string[];
            aws: components["schemas"]["CloudTrustAccount"][];
            description?: string;
        };
        CompileRequest: {
            policy: string;
            groups?: string[];
        };
        CompiledRule: {
            proto: string;
            port: string;
            host?: string;
            group?: string;
        };
        CompileResult: {
            valid: boolean;
            error?: string;
            invariants_ok: boolean;
            compiled?: {
                inbound: components["schemas"]["CompiledRule"][];
                outbound: components["schemas"]["CompiledRule"][];
            };
        };
        ReachabilityRequest: {
            policy: string;
            from: string;
            to: string;
            /** @description tcp|udp|icmp|any (default any) */
            proto?: string;
            /** @description any|N (default any) */
            port?: string;
        };
        ReachabilityDecision: {
            allowed: boolean;
            /** @description rule | baseline-control-plane | baseline-icmp | default-deny */
            reason: string;
            rule?: components["schemas"]["PolicyRule"];
            nearest?: components["schemas"]["PolicyRule"];
        };
        MatrixRequest: {
            policy: string;
            /** @description defaults to the groups named in the policy */
            groups?: string[];
        };
        Flow: {
            proto: string;
            port: string;
        };
        MatrixCell: {
            from: string;
            to: string;
            flows: components["schemas"]["Flow"][];
            /** @description to is the control plane (always reachable) */
            baseline: boolean;
        };
        ReachabilityMatrix: {
            groups: string[];
            cells: components["schemas"]["MatrixCell"][];
        };
        PolicyTestRequest: {
            policy: string;
            /** @description assert allow|deny <from> -> <to> <proto> <port> per line */
            tests: string;
        };
        PolicyTestAssertion: {
            expect: boolean;
            from: string;
            to: string;
            proto: string;
            port: string;
            line: number;
        };
        PolicyTestResult: {
            assertion: components["schemas"]["PolicyTestAssertion"];
            got: boolean;
            pass: boolean;
            reason: string;
        };
        PolicyTestResults: {
            results: components["schemas"]["PolicyTestResult"][];
            passed: number;
            failed: number;
            ok: boolean;
        };
        LighthouseAdd: {
            overlay_ip: string;
            hostname?: string;
            public_addrs: string[];
        };
        LighthouseReplace: {
            public_addrs: string[];
        };
        RolloutView: {
            /** Format: int64 */
            id: number;
            description?: string;
            target_version: number;
            prev_version: number;
            /** @description canary | widening | completed | rolledback (operator-abort lands as rolledback) */
            state: string;
            active_wave: number;
            wave_size: number;
            min_healthy: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
            note?: string;
        };
        RolloutHost: {
            overlay_ip: string;
            wave: number;
            /** @description waiting | converged | failed | reverted */
            status: string;
        };
        RolloutStatus: {
            active: boolean;
            rollout?: components["schemas"]["RolloutView"];
            hosts: components["schemas"]["RolloutHost"][];
        };
        RolloutStart: {
            target_version: number;
            prev_version?: number;
            hosts: string[];
            canary_size?: number;
            wave_size?: number;
            min_healthy?: number;
            observe_seconds?: number;
            missing_after_seconds?: number;
            description?: string;
        };
        RolloutStepResult: {
            changed: boolean;
            status: components["schemas"]["RolloutStatus"];
        };
        JoinKey: {
            name: string;
            groups: string[];
            sub_range?: string;
            max_uses: number;
            used_count: number;
            auto_issue: boolean;
            ephemeral: boolean;
            quota_per_hour: number;
            /** Format: date-time */
            expires_at?: string;
            state: string;
            /** Format: date-time */
            created_at: string;
        };
        JoinKeyList: {
            joinkeys: components["schemas"]["JoinKey"][];
            count: number;
        };
        JoinKeyCreate: {
            name: string;
            groups?: string[];
            sub_range?: string;
            max_uses?: number;
            ttl_seconds?: number;
            auto_issue?: boolean;
            ephemeral?: boolean;
            quota_per_hour?: number;
        };
        JoinKeyCreated: {
            /** @description the join-key secret — shown ONCE */
            secret: string;
            joinkey: components["schemas"]["JoinKey"];
        };
        EnrollmentView: {
            enrollment_id: string;
            device_name: string;
            /** @description fingerprint of the host pubkey; the key bytes are never returned */
            pubkey_hash: string;
            method: string;
            join_key_id?: number;
            groups: string[];
            /** @description pending | issued | denied */
            status: string;
            overlay_ip?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            decided_at?: string;
            approver?: string;
            /** @description cloud-attestation provider, e.g. aws (M5) */
            attest_provider?: string;
            /** @description attested account/subscription/project */
            attest_account?: string;
            /** @description attested ARN/principal/service-account */
            attest_principal?: string;
            attest_region?: string;
            /** Format: date-time */
            verified_at?: string;
        };
        EnrollmentList: {
            enrollments: components["schemas"]["EnrollmentView"][];
            /** @description page size — NOT the queue total */
            count: number;
            /** @description keyset cursor for the next page; absent on the last page */
            next_after?: number;
        };
        EnrollDecision: {
            enrollment_id: string;
            /** @description issued | denied */
            status: string;
            overlay_ip?: string;
        };
    };
    responses: {
        /** @description No / invalid admin identity. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description An error. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getFleetHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The health verdict and the counts behind it. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FleetHealth"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listDevices: {
        parameters: {
            query?: {
                limit?: number;
                /** @description cursor: overlay_ip of the last row from the previous page */
                after?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of devices. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listAudit: {
        parameters: {
            query?: {
                limit?: number;
                /** @description cursor: return entries with seq < this */
                before?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of audit entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    verifyAudit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The verification result (verified or tampered). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditVerify"];
                };
            };
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["Problem"];
        };
    };
    listLighthouses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All registered lighthouses. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LighthouseList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    addLighthouse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LighthouseAdd"];
            };
        };
        responses: {
            /** @description The registered lighthouse. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lighthouse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    listApprovals: {
        parameters: {
            query?: {
                /** @description filter by state (pending|committed|denied|failed) */
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending/decided changes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The change + sign-offs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalDetail"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["Problem"];
        };
    };
    approveChange: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The updated change (committed when quorum is met). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    denyChange: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DenyRequest"];
            };
        };
        responses: {
            /** @description The denied change. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    getActivePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The active policy, or {published:false} when none. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivePolicy"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    proposePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposeRequest"];
            };
        };
        responses: {
            /** @description The opened change (proposer = the authenticated principal). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
        };
    };
    getActiveCloudTrust: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The active cloud-trust config, or {published:false} when none. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudTrustActive"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    proposeCloudTrust: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloudTrustProposeRequest"];
            };
        };
        responses: {
            /** @description The opened change (proposer = the authenticated principal). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
        };
    };
    compilePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompileRequest"];
            };
        };
        responses: {
            /** @description Validity, invariants, and the compiled per-host firewall. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompileResult"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
        };
    };
    policyReachability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReachabilityRequest"];
            };
        };
        responses: {
            /** @description The reachability decision (granting rule, or default-deny + nearest miss). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReachabilityDecision"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
        };
    };
    policyMatrix: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatrixRequest"];
            };
        };
        responses: {
            /** @description The reachability matrix. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReachabilityMatrix"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
        };
    };
    policyTests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyTestRequest"];
            };
        };
        responses: {
            /** @description Per-assertion results + pass/fail tally. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyTestResults"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
        };
    };
    replaceLighthouse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LighthouseReplace"];
            };
        };
        responses: {
            /** @description The updated lighthouse. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lighthouse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    removeLighthouse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        overlay_ip: string;
                        removed: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    getCurrentRollout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current rollout, or {active:false} when none. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolloutStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    startRollout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RolloutStart"];
            };
        };
        responses: {
            /** @description The started rollout. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolloutView"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    stepRollout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Whether the state changed, plus the current status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolloutStepResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
        };
    };
    abortRollout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aborted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        aborted: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    listJoinKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All join keys. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinKeyList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createJoinKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinKeyCreate"];
            };
        };
        responses: {
            /** @description The created key + its one-time secret. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinKeyCreated"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    revokeJoinKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        name: string;
                        revoked: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    listEnrollments: {
        parameters: {
            query?: {
                /** @description pending (default) | issued | denied */
                status?: string;
                /** @description page size (1..2000, default 200) */
                limit?: number;
                /** @description keyset cursor: return rows with id greater than this (from next_after) */
                after?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of enrollments in the requested status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    approveEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description the enrollment_id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollDecision"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            501: components["responses"]["Problem"];
        };
    };
    denyEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description the enrollment_id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DenyRequest"];
            };
        };
        responses: {
            /** @description Denied. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollDecision"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
}
