/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated admin principal. */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/fleet/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server-computed fleet health rollup. */
        get: operations["getFleetHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Device inventory (from heartbeats), keyset-paginated on overlay_ip.
         * @description Each row carries provenance (how the host joined) and the groups it was issued, from its authoritative (latest issued) enrollment. Optional scope filters (provider, attest_account, join_key) and the health-condition filter narrow the list; the condition filter is the dashboard "why" drill-down, computed with the same thresholds as /fleet/health.
         */
        get: operations["listDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit log, newest first, cursor-paginated. */
        get: operations["listAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Audit-chain integrity (in-DB scope).
         * @description "verified" = clean; "tampered" = a genuine integrity failure; a 503 means the check could not run (NOT a claim of tampering). In-DB scope only; it cannot detect tail-truncation until WORM anchoring (impl 2.13) is configured.
         */
        get: operations["verifyAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/lighthouses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The lighthouse discovery fleet. */
        get: operations["listLighthouses"];
        put?: never;
        /** Register a lighthouse. */
        post: operations["addLighthouse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The dual-control approvals inbox (all kinds). */
        get: operations["listApprovals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/approvals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A change with its sign-offs (payload included). */
        get: operations["getApproval"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/approvals/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a change as the authenticated principal (distinct-approver enforced). */
        post: operations["approveChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/approvals/{id}/deny": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deny (veto) a change as the authenticated principal. */
        post: operations["denyChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/policy/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The published fleet policy (latest committed policy.publish). */
        get: operations["getActivePolicy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/policy/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate + invariant-check a policy, then open a dual-control change. */
        post: operations["proposePolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/cloudtrust/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The published cloud-attestation trust config (latest committed cloudtrust.publish). */
        get: operations["getActiveCloudTrust"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/cloudtrust/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a cloud-trust config, then open a dual-control change. */
        post: operations["proposeCloudTrust"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/usertrust/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The published SSO user-trust config (latest committed usertrust.publish, ADR 0004). */
        get: operations["getActiveUserTrust"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/usertrust/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate an SSO user-trust config, then open a dual-control change. */
        post: operations["proposeUserTrust"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/policy/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dry-run compile a draft policy for a host's groups (live analysis). */
        post: operations["compilePolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/policy/reachability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Can `from` reach `to` on proto/port under a draft policy? (A1 analysis) */
        post: operations["policyReachability"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/policy/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The all-pairs group×group reachability grid for a draft policy. (A1 analysis) */
        post: operations["policyMatrix"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/policy/tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate reachability assertions against a draft policy. (A1 analysis) */
        post: operations["policyTests"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/policy/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Flow delta (active vs draft) + blast radius. (A1.2 analysis)
         * @description The user-rule reachability flows added/removed between the active published policy and the draft, plus the blast radius — the real hosts whose compiled firewall would change. Dry-run; read-only.
         */
        post: operations["policyDiff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/lighthouses/{ip}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Re-address (and re-activate) a lighthouse. */
        put: operations["replaceLighthouse"];
        post?: never;
        /** Retire a lighthouse (refuses the last active one). */
        delete: operations["removeLighthouse"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/rollouts/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current staged rollout + per-host wave status. */
        get: operations["getCurrentRollout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/rollouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a staged canary rollout. */
        post: operations["startRollout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/rollouts/current/step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Force one rollout evaluation (cron/ops). */
        post: operations["stepRollout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/rollouts/current/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abort the active rollout (touched hosts revert to prev). */
        post: operations["abortRollout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The nebula + pilot release registries, each with its current rollout (ADR 0003 1c/3c). Binaries are added via the CLI; this is read + stage only. */
        get: operations["listReleases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/releases/{kind}/rollouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage a fleet upgrade to a registered release generation on the kind's canary lane. */
        post: operations["startReleaseRollout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/releases/{kind}/rollouts/current/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abort the kind's active release rollout (touched hosts revert to the previous generation). */
        post: operations["abortReleaseRollout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/joinkeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List join keys (secrets never returned). */
        get: operations["listJoinKeys"];
        put?: never;
        /** Create a join key; the secret is returned ONCE. */
        post: operations["createJoinKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/joinkeys/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit an active join key's config (groups, caps, auto-issue). Secret/name/used-count are immutable. */
        patch: operations["updateJoinKey"];
        trace?: never;
    };
    "/admin/v1/joinkeys/{name}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a join key by name. */
        post: operations["revokeJoinKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The enrollment approval queue (keyset-paginated on id). */
        get: operations["listEnrollments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/enrollments/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a pending enrollment (issues a cert). Requires issuance mode. */
        post: operations["approveEnrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/enrollments/{id}/deny": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a pending enrollment (no signing). */
        post: operations["denyEnrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/ipam/netblocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List netblocks with per-block utilization (ADR 0010 IPAM). */
        get: operations["listNetblocks"];
        put?: never;
        /** Carve a new named netblock. Requires ipam:manage + step-up MFA. */
        post: operations["createNetblock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/ipam/netblocks/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Growth-aware placement suggestion for a new /N netblock. */
        get: operations["suggestNetblock"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/ipam/netblocks/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a netblock (protected or in-use blocks are refused). Requires ipam:manage + step-up MFA. */
        delete: operations["removeNetblock"];
        options?: never;
        head?: never;
        /** Edit a netblock's CIDR/description. Both optional; protected blocks refused. Requires ipam:manage + step-up MFA. */
        patch: operations["updateNetblock"];
        trace?: never;
    };
    "/admin/v1/ipam/allocations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Allocations within a netblock (overlay/heat data). */
        get: operations["listIPAMAllocations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            title: string;
            status: number;
            detail?: string;
        };
        Identity: {
            principal: string;
            roles: string[];
            /** Format: date-time */
            mfa_satisfied_at?: string;
        };
        /** @enum {string} */
        Severity: "info" | "degraded" | "critical";
        Reason: {
            code: string;
            severity: components["schemas"]["Severity"];
            count: number;
            detail: string;
            link?: string;
        };
        FleetHealth: {
            /** @enum {string} */
            status: "healthy" | "degraded" | "critical";
            reasons: components["schemas"]["Reason"][];
            totals: {
                total: number;
                expired: number;
                expiring: number;
                stale: number;
                clock_skewed: number;
                unhealthy: number;
            };
            rollout_state?: string;
            audit_ok: boolean;
        };
        Device: {
            overlay_ip: string;
            name: string;
            pilot_version?: string;
            nebula_version?: string;
            /** Format: date-time */
            cert_not_after?: string;
            applied_bundle_version: number;
            clock_offset_ms: number;
            health?: string;
            /** Format: date-time */
            last_seen?: string;
            /** @description provenance: cloud-attestation provider, e.g. aws (attested hosts only) */
            attest_provider?: string;
            /** @description provenance: attested account/subscription/project */
            attest_account?: string;
            /** @description provenance: attested ARN/principal/service-account */
            attest_principal?: string;
            attest_region?: string;
            /** @description provenance: join-key name for token-enrolled hosts */
            join_key_name?: string;
            /** @description groups the host was issued (from its authoritative enrollment) */
            groups?: string[];
            /** @description host joined via an ephemeral join key (shorter cert TTL; foundation for auto-reaping, impl 2.12) */
            ephemeral?: boolean;
        };
        DeviceList: {
            devices: components["schemas"]["Device"][];
            /** @description page size, NOT the fleet total */
            count: number;
            /** @description cursor for the next page (present only when more rows exist) */
            next_after?: string;
        };
        AuditRow: {
            /** Format: int64 */
            seq: number;
            /** Format: date-time */
            ts: string;
            actor: string;
            action: string;
            target?: string;
            details?: string;
        };
        AuditList: {
            entries: components["schemas"]["AuditRow"][];
            count: number;
            /**
             * Format: int64
             * @description cursor for the next (older) page
             */
            next_before?: number;
        };
        AuditVerify: {
            /** @enum {string} */
            status: "verified" | "tampered";
            ok: boolean;
            /** Format: int64 */
            verified_rows: number;
            scope: string;
            detail?: string;
        };
        Lighthouse: {
            overlay_ip: string;
            hostname?: string;
            state: string;
            public_addrs: string[];
        };
        LighthouseList: {
            lighthouses: components["schemas"]["Lighthouse"][];
            count: number;
        };
        Change: {
            /** Format: int64 */
            id: number;
            kind: string;
            target?: string;
            /** @description pending | committing | committed | denied | failed */
            state: string;
            quorum: number;
            proposer: string;
            payload_sha256: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            decided_at?: string;
            /** @description the proposed content (e.g. the policy DSL); included on detail, not in lists */
            payload?: string;
        };
        Signoff: {
            actor: string;
            /** @enum {string} */
            decision: "approve" | "deny";
            /** Format: date-time */
            created_at: string;
        };
        ApprovalList: {
            approvals: components["schemas"]["Change"][];
            count: number;
        };
        ApprovalDetail: {
            change: components["schemas"]["Change"];
            signoffs: components["schemas"]["Signoff"][];
        };
        ProposeRequest: {
            /** @description the firewall policy DSL */
            policy: string;
            description?: string;
        };
        DenyRequest: {
            reason?: string;
        };
        PolicyRule: {
            from: string;
            to: string;
            proto: string;
            port: string;
        };
        ActivePolicy: {
            published: boolean;
            /** Format: int64 */
            change_id?: number;
            hash?: string;
            text?: string;
            rules?: components["schemas"]["PolicyRule"][];
        };
        CloudTrustAccount: {
            /** @description AWS account id (exact match) */
            account: string;
            /** @description allowed caller-ARN globs; empty = any ARN in the account */
            arn_patterns?: string[];
            /** @description groups granted to hosts attesting from this account */
            groups?: string[];
            /** @description issue immediately vs queue for manual approval */
            auto_issue?: boolean;
            /** @description named IPAM netblock hosts from this scope draw their overlay IP from (ADR 0010); empty = the default block */
            netblock?: string;
        };
        CloudTrustActive: {
            published: boolean;
            /** Format: int64 */
            change_id?: number;
            hash?: string;
            /** @description granted to every validly-attested host */
            default_groups?: string[];
            aws?: components["schemas"]["CloudTrustAccount"][];
        };
        CloudTrustProposeRequest: {
            default_groups?: string[];
            aws: components["schemas"]["CloudTrustAccount"][];
            description?: string;
        };
        IDPEntry: {
            /** @description IdP/tenant realm; matched EXACTLY against the assertion issuer (ADR 0004 S2) */
            realm: string;
            /** @description SAML/OIDC AD-group name this entry keys on */
            directory_group: string;
            /** @description nebula groups granted to a host matching this entry, on top of default_groups */
            mesh_groups?: string[];
            /** @description issue immediately vs queue for manual approval (defaults off, S8) */
            auto_issue?: boolean;
            /** @description named IPAM netblock matching hosts draw their overlay IP from (ADR 0010); empty = the default block */
            netblock?: string;
        };
        UserTrustActive: {
            published: boolean;
            /** Format: int64 */
            change_id?: number;
            hash?: string;
            /** @description granted to every validly SSO-enrolled host */
            default_groups?: string[];
            idp_entries?: components["schemas"]["IDPEntry"][];
        };
        UserTrustProposeRequest: {
            default_groups?: string[];
            idp_entries: components["schemas"]["IDPEntry"][];
            description?: string;
        };
        CompileRequest: {
            policy: string;
            groups?: string[];
        };
        CompiledRule: {
            proto: string;
            port: string;
            host?: string;
            group?: string;
        };
        CompileResult: {
            valid: boolean;
            error?: string;
            invariants_ok: boolean;
            compiled?: {
                inbound: components["schemas"]["CompiledRule"][];
                outbound: components["schemas"]["CompiledRule"][];
            };
        };
        ReachabilityRequest: {
            policy: string;
            from: string;
            to: string;
            /** @description tcp|udp|icmp|any (default any) */
            proto?: string;
            /** @description any|N (default any) */
            port?: string;
        };
        ReachabilityDecision: {
            allowed: boolean;
            /** @description rule | baseline-control-plane | baseline-icmp | default-deny */
            reason: string;
            rule?: components["schemas"]["PolicyRule"];
            nearest?: components["schemas"]["PolicyRule"];
        };
        MatrixRequest: {
            policy: string;
            /** @description defaults to the groups named in the policy */
            groups?: string[];
        };
        Flow: {
            proto: string;
            port: string;
        };
        MatrixCell: {
            from: string;
            to: string;
            flows: components["schemas"]["Flow"][];
            /** @description to is the control plane (always reachable) */
            baseline: boolean;
        };
        ReachabilityMatrix: {
            groups: string[];
            cells: components["schemas"]["MatrixCell"][];
        };
        PolicyTestRequest: {
            policy: string;
            /** @description assert allow|deny <from> -> <to> <proto> <port> per line */
            tests: string;
        };
        PolicyTestAssertion: {
            expect: boolean;
            from: string;
            to: string;
            proto: string;
            port: string;
            line: number;
        };
        PolicyTestResult: {
            assertion: components["schemas"]["PolicyTestAssertion"];
            got: boolean;
            pass: boolean;
            reason: string;
        };
        PolicyTestResults: {
            results: components["schemas"]["PolicyTestResult"][];
            passed: number;
            failed: number;
            ok: boolean;
        };
        PolicyDiffRequest: {
            /** @description the draft DSL; diffed against the active committed policy */
            policy: string;
        };
        FlowDelta: {
            /** @description literal rule from-group (may be 'any') */
            from: string;
            /** @description literal rule to-group (may be 'any') */
            to: string;
            flow: components["schemas"]["Flow"];
        };
        BlastRadius: {
            /** @description true number of hosts whose firewall changes */
            count: number;
            /** @description total issued hosts in the fleet */
            total: number;
            /** @description affected overlay IPs (capped; count is authoritative) */
            hosts?: string[];
            /** @description true if the hosts list was capped */
            truncated?: boolean;
        };
        PolicyDiff: {
            /** @description the active-policy identity the diff was computed against (published:false if none) */
            active: {
                published: boolean;
                /** Format: int64 */
                change_id?: number;
                hash?: string;
            };
            added: components["schemas"]["FlowDelta"][];
            removed: components["schemas"]["FlowDelta"][];
            blast: components["schemas"]["BlastRadius"];
            /** @description present if the draft violates a publish invariant (it can be previewed but never committed) */
            warning?: string;
        };
        LighthouseAdd: {
            overlay_ip: string;
            hostname?: string;
            public_addrs: string[];
        };
        LighthouseReplace: {
            public_addrs: string[];
        };
        RolloutView: {
            /** Format: int64 */
            id: number;
            description?: string;
            target_version: number;
            prev_version: number;
            /** @description canary | widening | completed | rolledback (operator-abort lands as rolledback) */
            state: string;
            active_wave: number;
            wave_size: number;
            min_healthy: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
            note?: string;
        };
        RolloutHost: {
            overlay_ip: string;
            wave: number;
            /** @description waiting | converged | failed | reverted */
            status: string;
        };
        RolloutStatus: {
            active: boolean;
            rollout?: components["schemas"]["RolloutView"];
            hosts: components["schemas"]["RolloutHost"][];
        };
        RolloutStart: {
            target_version: number;
            prev_version?: number;
            hosts: string[];
            canary_size?: number;
            wave_size?: number;
            min_healthy?: number;
            observe_seconds?: number;
            missing_after_seconds?: number;
            description?: string;
        };
        RolloutStepResult: {
            changed: boolean;
            status: components["schemas"]["RolloutStatus"];
        };
        ReleaseView: {
            /**
             * Format: int64
             * @description the generation the rollout lane stages
             */
            gen: number;
            version: string;
            /** @description the integrity anchor the pilot verifies before swap */
            sha256: string;
            /** @description where the pilot fetches the artifact (operator-hosted) */
            url: string;
            /** @description candidate | current | superseded */
            status: string;
            note?: string;
            /** Format: date-time */
            created_at: string;
        };
        ReleaseLane: {
            releases: components["schemas"]["ReleaseView"][];
            /** @description the live fleet-desired generation (0 = none) */
            current_gen: number;
            /** @description the lane's current rollout, or null when none */
            rollout?: components["schemas"]["RolloutStatus"] | null;
        };
        ReleasesResponse: {
            nebula: components["schemas"]["ReleaseLane"];
            pilot: components["schemas"]["ReleaseLane"];
        };
        ReleaseRolloutStart: {
            /** @description the registered generation to stage */
            gen: number;
            canary_size?: number;
            wave_size?: number;
            observe_seconds?: number;
            missing_after_seconds?: number;
        };
        JoinKey: {
            name: string;
            groups: string[];
            sub_range?: string;
            max_uses: number;
            used_count: number;
            auto_issue: boolean;
            ephemeral: boolean;
            quota_per_hour: number;
            /** Format: date-time */
            expires_at?: string;
            state: string;
            /** Format: date-time */
            created_at: string;
        };
        JoinKeyList: {
            joinkeys: components["schemas"]["JoinKey"][];
            count: number;
        };
        JoinKeyCreate: {
            name: string;
            groups?: string[];
            sub_range?: string;
            max_uses?: number;
            ttl_seconds?: number;
            auto_issue?: boolean;
            ephemeral?: boolean;
            quota_per_hour?: number;
        };
        /** @description All fields optional; an omitted field is left unchanged (active keys only). name/secret/used_count/state are immutable. */
        JoinKeyUpdate: {
            groups?: string[];
            sub_range?: string;
            /** @description 0 = unlimited */
            max_uses?: number;
            /** @description 0 = no rate limit */
            quota_per_hour?: number;
            auto_issue?: boolean;
            ephemeral?: boolean;
            /** @description relative, re-based from now; 0 = never expire */
            ttl_seconds?: number;
        };
        JoinKeyCreated: {
            /** @description the join-key secret — shown ONCE */
            secret: string;
            joinkey: components["schemas"]["JoinKey"];
        };
        Netblock: {
            name: string;
            /** @description the netblock's IPv4 CIDR, e.g. 10.44.20.0/24 */
            cidr: string;
            /** @enum {string} */
            kind: "reserved" | "default" | "named";
            description?: string;
            /** @description central/default cannot be edited or removed */
            protected: boolean;
            /** @description usable host count (CIDR size minus the network address) */
            capacity: number;
            /** @description current allocations inside the CIDR */
            allocated: number;
            /** @description live addresses: allocations whose host has heartbeated within the fleet stale window (StaleAfter); a subset of allocated, decaying as hosts go stale */
            used: number;
            /** @description allocated / capacity * 100 (one decimal) */
            pct: number;
            /** Format: date-time */
            created_at: string;
            created_by?: string;
        };
        NetblockList: {
            netblocks: components["schemas"]["Netblock"][];
            count: number;
            /** @description the configured overlay pool CIDR (e.g. 10.44.0.0/16); the UI uses this as the address-map extent. Absent/empty when no pool is configured. */
            pool?: string;
        };
        NetblockCreateRequest: {
            name: string;
            /** @description the IPv4 CIDR to carve, e.g. 10.44.20.0/24 */
            cidr: string;
            description?: string;
        };
        /** @description Both fields optional; an omitted field is left unchanged. Protected (central/default) blocks are refused. */
        NetblockUpdateRequest: {
            cidr?: string;
            description?: string;
        };
        NetblockSuggestion: {
            /** @description the requested prefix length */
            prefix: number;
            /** @description a growth-aware placement CIDR for that size */
            cidr: string;
        };
        Allocation: {
            ip: string;
            device?: string;
            /** @description token | aws-sigv4 | sso | genesis */
            method?: string;
            /** Format: date-time */
            allocated_at?: string;
        };
        AllocationList: {
            netblock: string;
            cidr: string;
            allocations: components["schemas"]["Allocation"][];
            count: number;
        };
        EnrollmentView: {
            enrollment_id: string;
            device_name: string;
            /** @description fingerprint of the host pubkey; the key bytes are never returned */
            pubkey_hash: string;
            method: string;
            join_key_id?: number;
            /** @description name of the join key (resolved from join_key_id); token enrollments only */
            join_key_name?: string;
            groups: string[];
            /** @description pending | issued | denied */
            status: string;
            /** @description enrollment via an ephemeral join key (shorter cert TTL; foundation for auto-reaping, impl 2.12) */
            ephemeral?: boolean;
            overlay_ip?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            decided_at?: string;
            approver?: string;
            /** @description cloud-attestation provider, e.g. aws (M5) */
            attest_provider?: string;
            /** @description attested account/subscription/project */
            attest_account?: string;
            /** @description attested ARN/principal/service-account */
            attest_principal?: string;
            attest_region?: string;
            /** Format: date-time */
            verified_at?: string;
        };
        EnrollmentList: {
            enrollments: components["schemas"]["EnrollmentView"][];
            /** @description page size — NOT the queue total */
            count: number;
            /** @description keyset cursor for the next page; absent on the last page */
            next_after?: number;
        };
        EnrollDecision: {
            enrollment_id: string;
            /** @description issued | denied */
            status: string;
            overlay_ip?: string;
        };
    };
    responses: {
        /** @description No / invalid admin identity. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description An error. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getFleetHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The health verdict and the counts behind it. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FleetHealth"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listDevices: {
        parameters: {
            query?: {
                limit?: number;
                /** @description cursor: overlay_ip of the last row from the previous page */
                after?: string;
                /** @description scope: attestation provider, e.g. aws */
                provider?: string;
                /** @description scope: attested account/subscription/project */
                attest_account?: string;
                /** @description scope: join-key name the host token-enrolled with */
                join_key?: string;
                /** @description health drill-down (matches the dashboard verdict) */
                condition?: "expired" | "expiring" | "stale" | "clock_skewed" | "unhealthy";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of devices. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceList"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listAudit: {
        parameters: {
            query?: {
                limit?: number;
                /** @description cursor: return entries with seq < this */
                before?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of audit entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    verifyAudit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The verification result (verified or tampered). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditVerify"];
                };
            };
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["Problem"];
        };
    };
    listLighthouses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All registered lighthouses. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LighthouseList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    addLighthouse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LighthouseAdd"];
            };
        };
        responses: {
            /** @description The registered lighthouse. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lighthouse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    listApprovals: {
        parameters: {
            query?: {
                /** @description filter by state (pending|committed|denied|failed) */
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending/decided changes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The change + sign-offs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalDetail"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["Problem"];
        };
    };
    approveChange: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The updated change (committed when quorum is met). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    denyChange: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DenyRequest"];
            };
        };
        responses: {
            /** @description The denied change. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    getActivePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The active policy, or {published:false} when none. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivePolicy"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    proposePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposeRequest"];
            };
        };
        responses: {
            /** @description The opened change (proposer = the authenticated principal). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
        };
    };
    getActiveCloudTrust: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The active cloud-trust config, or {published:false} when none. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudTrustActive"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    proposeCloudTrust: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloudTrustProposeRequest"];
            };
        };
        responses: {
            /** @description The opened change (proposer = the authenticated principal). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
        };
    };
    getActiveUserTrust: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The active user-trust config, or {published:false} when none. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserTrustActive"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    proposeUserTrust: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserTrustProposeRequest"];
            };
        };
        responses: {
            /** @description The opened change (proposer = the authenticated principal). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
        };
    };
    compilePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompileRequest"];
            };
        };
        responses: {
            /** @description Validity, invariants, and the compiled per-host firewall. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompileResult"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
        };
    };
    policyReachability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReachabilityRequest"];
            };
        };
        responses: {
            /** @description The reachability decision (granting rule, or default-deny + nearest miss). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReachabilityDecision"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
        };
    };
    policyMatrix: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatrixRequest"];
            };
        };
        responses: {
            /** @description The reachability matrix. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReachabilityMatrix"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
        };
    };
    policyTests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyTestRequest"];
            };
        };
        responses: {
            /** @description Per-assertion results + pass/fail tally. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyTestResults"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
        };
    };
    policyDiff: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyDiffRequest"];
            };
        };
        responses: {
            /** @description Added/removed flows + blast radius. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDiff"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
        };
    };
    replaceLighthouse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LighthouseReplace"];
            };
        };
        responses: {
            /** @description The updated lighthouse. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lighthouse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    removeLighthouse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        overlay_ip: string;
                        removed: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    getCurrentRollout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current rollout, or {active:false} when none. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolloutStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    startRollout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RolloutStart"];
            };
        };
        responses: {
            /** @description The started rollout. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolloutView"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    stepRollout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Whether the state changed, plus the current status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolloutStepResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
        };
    };
    abortRollout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aborted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        aborted: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    listReleases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Both release lanes (registry rows + current gen + rollout). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleasesResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    startReleaseRollout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "nebula" | "pilot";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseRolloutStart"];
            };
        };
        responses: {
            /** @description The started rollout. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolloutView"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    abortReleaseRollout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "nebula" | "pilot";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aborted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        aborted: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    listJoinKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All join keys. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinKeyList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createJoinKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinKeyCreate"];
            };
        };
        responses: {
            /** @description The created key + its one-time secret. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinKeyCreated"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    updateJoinKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinKeyUpdate"];
            };
        };
        responses: {
            /** @description The updated key. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinKey"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    revokeJoinKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        name: string;
                        revoked: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    listEnrollments: {
        parameters: {
            query?: {
                /** @description pending (default) | issued | denied */
                status?: string;
                /** @description page size (1..2000, default 200) */
                limit?: number;
                /** @description keyset cursor: return rows with id greater than this (from next_after) */
                after?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of enrollments in the requested status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    approveEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description the enrollment_id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollDecision"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            501: components["responses"]["Problem"];
        };
    };
    denyEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description the enrollment_id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DenyRequest"];
            };
        };
        responses: {
            /** @description Denied. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollDecision"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    listNetblocks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All netblocks (central, default, named carves) + utilization. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetblockList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createNetblock: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NetblockCreateRequest"];
            };
        };
        responses: {
            /** @description The created netblock. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Netblock"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    suggestNetblock: {
        parameters: {
            query: {
                /** @description requested prefix length (1-32) */
                prefix: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A suggested CIDR for the requested size. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetblockSuggestion"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    removeNetblock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        name: string;
                        removed: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    updateNetblock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NetblockUpdateRequest"];
            };
        };
        responses: {
            /** @description The updated netblock. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Netblock"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    listIPAMAllocations: {
        parameters: {
            query: {
                /** @description the netblock name */
                netblock: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Allocations inside the netblock's CIDR. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllocationList"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
}
