// Package version exposes the harbor build identity (CalVer date + short commit + build time) and
// the embedded git changelog, both stamped/generated at build time. internal/adminapi serves these
// at GET /admin/v1/version, which drives the console's version badge + changelog page — so whatever
// the console shows is exactly the build running on this Harbor.
package version

import (
	_ "embed"
	"encoding/json"
)

// Stamped at build via -ldflags "-X github.com/jeks313/nebula-control-plane/internal/version.<X>=...".
// The defaults make an un-stamped (bare `go build`) build obvious.
var (
	Version   = "dev"     // CalVer build date, e.g. 2026.06.28
	Commit    = "none"    // short git sha, e.g. cb699d0c
	BuildTime = "unknown" // RFC3339 build timestamp
)

// changelogJSON is generated by deploy/scripts/gen-changelog.sh (git log -> JSON array, newest
// first) and embedded at build. A committed `[]` keeps a bare `go build` / CI green when the
// generator hasn't run.
//
//go:embed changelog.json
var changelogJSON []byte

// Change is one commit in the changelog.
type Change struct {
	Hash    string `json:"hash"`
	Date    string `json:"date"` // YYYY-MM-DD committer date
	Subject string `json:"subject"`
}

// Changelog returns the embedded commit log, newest first (nil if absent/unparseable).
func Changelog() []Change {
	var out []Change
	_ = json.Unmarshal(changelogJSON, &out)
	return out
}
