// Package genesis performs the control-plane bootstrap ceremony
// (implementation-plan M3.1): create the two trust roots — the **CA key** (signs
// certs) and the **config-signing key** (signs bundles, protocol spec §3/§6) —
// and issue the first lighthouse certificate, recording every step in the
// hash-chained audit log under two operator identities (a stand-in for real
// cryptographic dual-control, which is 2.11).
//
// P1 is preserved: the lighthouse generates its own key (via `pilot init`) and
// only its public key is handed to genesis; no host private key is centralized.
package genesis

import (
	"context"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/netip"
	"time"

	"github.com/jeks313/nebula-control-plane/internal/ipam"
	"github.com/jeks313/nebula-control-plane/internal/signer"
	"github.com/jeks313/nebula-control-plane/internal/store"
	"github.com/slackhq/nebula/cert"
)

// Params drives a genesis run.
type Params struct {
	OperatorA, OperatorB string // the two ceremony operators (must differ)
	CAName               string
	Pool                 netip.Prefix
	LighthouseName       string
	LighthouseIP         netip.Addr // reserved overlay IP (e.g. 100.64.0.1)
	LighthouseAddr       string     // public underlay addr (recorded for the static_host_map)
	LighthousePub        []byte     // the lighthouse's host public key PEM (P1: generated by it)
	CALifetime           time.Duration
	CertLifetime         time.Duration
	Now                  func() time.Time
}

// Result is what a genesis run produced (the operator persists these).
type Result struct {
	CACertPEM             []byte
	CAFingerprint         string
	ConfigSigningPubPEM   []byte
	ConfigSigningKeyID    string
	LighthouseCertPEM     []byte
	LighthouseFingerprint string
	LighthouseIP          netip.Addr
	ManifestJSON          []byte
}

type manifest struct {
	CreatedAt          string   `json:"created_at"`
	Operators          []string `json:"operators"`
	CAName             string   `json:"ca_name"`
	CAFingerprint      string   `json:"ca_fingerprint"`
	ConfigSigningKeyID string   `json:"config_signing_key_id"`
	Pool               string   `json:"pool"`
	Lighthouse         struct {
		Name        string `json:"name"`
		OverlayIP   string `json:"overlay_ip"`
		PublicAddr  string `json:"public_addr"`
		Fingerprint string `json:"fingerprint"`
	} `json:"lighthouse"`
}

// Run executes the ceremony against an already-migrated store, using caBackend
// to sign certs and configBackend as the bundle-signing key. Both backends must
// already hold their keys (software: freshly generated by the caller; HSM/KMS:
// pre-provisioned).
func Run(ctx context.Context, s *store.Store, caBackend, configBackend signer.Backend, p Params) (Result, error) {
	if p.Now == nil {
		p.Now = time.Now
	}
	if p.OperatorA == "" || p.OperatorB == "" || p.OperatorA == p.OperatorB {
		return Result{}, fmt.Errorf("genesis: two distinct operators are required")
	}
	now := p.Now()
	audit := func(actor, action, target, details string) error {
		_, err := s.AppendAudit(ctx, actor, action, target, details)
		return err
	}

	// 1. CA root.
	caCert, caPEM, err := signer.SelfSignCA(caBackend, signer.CATemplate{
		Name:      p.CAName,
		Networks:  []netip.Prefix{p.Pool},
		NotBefore: now.Add(-time.Hour),
		NotAfter:  now.Add(p.CALifetime),
	})
	if err != nil {
		return Result{}, err
	}
	caFP, _ := caCert.Fingerprint()
	caPub, _ := caBackend.PublicKey()
	if err := s.DB.Create(&store.Key{
		Name: p.CAName, Kind: "ca", Backend: "genesis", Curve: "P256",
		PublicKey: caPub, State: "active", CreatedAt: now.UnixNano(),
	}).Error; err != nil {
		return Result{}, fmt.Errorf("genesis: record CA key: %w", err)
	}
	if err := audit(p.OperatorA, "genesis-ca", p.CAName, fmt.Sprintf(`{"fingerprint":%q}`, caFP)); err != nil {
		return Result{}, err
	}

	// 2. Config-signing root (signs bundles; pinned by Pilot).
	configPub, err := configBackend.PublicKey()
	if err != nil {
		return Result{}, fmt.Errorf("genesis: config-signing public key: %w", err)
	}
	configPubPEM := cert.MarshalSigningPublicKeyToPEM(cert.Curve_P256, configPub)
	configKeyID := keyID(configPub)
	if err := s.DB.Create(&store.Key{
		Name: p.CAName + "-config-signing", Kind: "config-signing", Backend: "genesis", Curve: "P256",
		PublicKey: configPub, State: "active", CreatedAt: now.UnixNano(),
	}).Error; err != nil {
		return Result{}, fmt.Errorf("genesis: record config-signing key: %w", err)
	}
	if err := audit(p.OperatorB, "genesis-config-key", configKeyID, ""); err != nil {
		return Result{}, err
	}

	// 3. First lighthouse certificate (from its own public key — P1).
	pub, _, curve, err := cert.UnmarshalPublicKeyFromPEM(p.LighthousePub)
	if err != nil {
		return Result{}, fmt.Errorf("genesis: parse lighthouse public key: %w", err)
	}
	if curve != cert.Curve_P256 {
		return Result{}, fmt.Errorf("genesis: lighthouse key curve is %s, want P256", curve)
	}
	alloc, err := ipam.NewAllocator(s, ipam.Pool{Prefix: p.Pool})
	if err != nil {
		return Result{}, err
	}
	if err := alloc.AllocateSpecific(ctx, p.LighthouseName, p.LighthouseIP); err != nil {
		return Result{}, fmt.Errorf("genesis: reserve lighthouse IP: %w", err)
	}
	sg, err := signer.New(signer.Config{
		CACertPEM: caPEM, Backend: caBackend,
		Policy: signer.Policy{AllowedNetwork: p.Pool, MaxLifetime: p.CertLifetime},
		Audit:  func(c context.Context, a, ac, t, d string) error { _, e := s.AppendAudit(c, a, ac, t, d); return e },
	})
	if err != nil {
		return Result{}, err
	}
	nb := now.Add(-5 * time.Minute)
	lhCert, lhPEM, err := sg.Issue(ctx, p.OperatorA, signer.Template{
		Name:      p.LighthouseName,
		Networks:  []netip.Prefix{netip.PrefixFrom(p.LighthouseIP, p.Pool.Bits())},
		Groups:    []string{"lighthouse"},
		NotBefore: nb,
		NotAfter:  nb.Add(p.CertLifetime),
		PublicKey: pub,
	})
	if err != nil {
		return Result{}, fmt.Errorf("genesis: issue lighthouse cert: %w", err)
	}
	lhFP, _ := lhCert.Fingerprint()

	// 4. Manifest + completion record.
	var m manifest
	m.CreatedAt = now.UTC().Format(time.RFC3339)
	m.Operators = []string{p.OperatorA, p.OperatorB}
	m.CAName = p.CAName
	m.CAFingerprint = caFP
	m.ConfigSigningKeyID = configKeyID
	m.Pool = p.Pool.String()
	m.Lighthouse.Name = p.LighthouseName
	m.Lighthouse.OverlayIP = p.LighthouseIP.String()
	m.Lighthouse.PublicAddr = p.LighthouseAddr
	m.Lighthouse.Fingerprint = lhFP
	manifestJSON, _ := json.MarshalIndent(m, "", "  ")
	if err := audit(p.OperatorB, "genesis-complete", p.CAName,
		fmt.Sprintf(`{"ca":%q,"config_key":%q,"lighthouse":%q}`, caFP, configKeyID, lhFP)); err != nil {
		return Result{}, err
	}

	return Result{
		CACertPEM:             caPEM,
		CAFingerprint:         caFP,
		ConfigSigningPubPEM:   configPubPEM,
		ConfigSigningKeyID:    configKeyID,
		LighthouseCertPEM:     lhPEM,
		LighthouseFingerprint: lhFP,
		LighthouseIP:          p.LighthouseIP,
		ManifestJSON:          manifestJSON,
	}, nil
}

// keyID is the base64url SHA-256 of a public key — the same identifier the
// protocol spec uses for kid/pubkey_hash.
func keyID(pub []byte) string {
	h := sha256.Sum256(pub)
	return base64.RawURLEncoding.EncodeToString(h[:])
}
