// Package genesis performs the control-plane bootstrap ceremony
// (implementation-plan M3.1): create the two trust roots — the **CA key** (signs
// certs) and the **config-signing key** (signs bundles, protocol spec §3/§6) —
// and issue the first lighthouse certificate, recording every step in the
// hash-chained audit log under two operator identities (a stand-in for real
// cryptographic dual-control, which is 2.11).
//
// P1 is preserved: the lighthouse generates its own key (via `pilot init`) and
// only its public key is handed to genesis; no host private key is centralized.
package genesis

import (
	"context"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/netip"
	"time"

	"github.com/jeks313/nebula-control-plane/internal/ipam"
	"github.com/jeks313/nebula-control-plane/internal/policy"
	"github.com/jeks313/nebula-control-plane/internal/signer"
	"github.com/jeks313/nebula-control-plane/internal/store"
	"github.com/slackhq/nebula/cert"
)

// Params drives a genesis run.
type Params struct {
	OperatorA, OperatorB string // the two ceremony operators (must differ)
	CAName               string
	Pool                 netip.Prefix
	LighthouseName       string
	LighthouseIP         netip.Addr // reserved overlay IP (e.g. 100.64.0.1)
	LighthouseAddr       string     // public underlay addr (recorded for the static_host_map)
	LighthousePub        []byte     // the lighthouse's host public key PEM (P1: generated by it)
	// Optional first Core (control-plane) node, symmetric with the lighthouse. When
	// CorePub is set, genesis issues Core's cert in group control-plane and reserves
	// its IP. The firewall baseline (policy §6.3) routes every host to
	// group:control-plane, so a Core node MUST hold that group or heartbeat/renew is
	// unreachable — minting it here keeps the bootstrap self-consistent with the
	// baseline instead of relying on a manual out-of-band issue-cert step.
	CoreName     string
	CoreIP       netip.Addr // reserved overlay IP for Core (e.g. 100.64.0.2)
	CorePub      []byte     // Core's host public key PEM (P1: generated by it); empty = skip
	CALifetime   time.Duration
	CertLifetime time.Duration
	Now          func() time.Time
}

// Result is what a genesis run produced (the operator persists these).
type Result struct {
	CACertPEM             []byte
	CAFingerprint         string
	ConfigSigningPubPEM   []byte
	ConfigSigningKeyID    string
	LighthouseCertPEM     []byte
	LighthouseFingerprint string
	LighthouseIP          netip.Addr
	// Core (control-plane) — populated only when CorePub was provided.
	CoreCertPEM     []byte
	CoreFingerprint string
	CoreIP          netip.Addr
	ManifestJSON    []byte
}

type manifestNode struct {
	Name        string `json:"name"`
	OverlayIP   string `json:"overlay_ip"`
	PublicAddr  string `json:"public_addr,omitempty"`
	Fingerprint string `json:"fingerprint"`
}

type manifest struct {
	CreatedAt          string        `json:"created_at"`
	Operators          []string      `json:"operators"`
	CAName             string        `json:"ca_name"`
	CAFingerprint      string        `json:"ca_fingerprint"`
	ConfigSigningKeyID string        `json:"config_signing_key_id"`
	Pool               string        `json:"pool"`
	Lighthouse         manifestNode  `json:"lighthouse"`
	Core               *manifestNode `json:"core,omitempty"` // present only if Core was issued
}

// Run executes the ceremony against an already-migrated store, using caBackend
// to sign certs and configBackend as the bundle-signing key. Both backends must
// already hold their keys (software: freshly generated by the caller; HSM/KMS:
// pre-provisioned).
func Run(ctx context.Context, s *store.Store, caBackend, configBackend signer.Backend, p Params) (Result, error) {
	if p.Now == nil {
		p.Now = time.Now
	}
	if p.OperatorA == "" || p.OperatorB == "" || p.OperatorA == p.OperatorB {
		return Result{}, fmt.Errorf("genesis: two distinct operators are required")
	}
	now := p.Now()
	audit := func(actor, action, target, details string) error {
		_, err := s.AppendAudit(ctx, actor, action, target, details)
		return err
	}

	// 1. CA root.
	caCert, caPEM, err := signer.SelfSignCA(caBackend, signer.CATemplate{
		Name:      p.CAName,
		Networks:  []netip.Prefix{p.Pool},
		NotBefore: now.Add(-time.Hour),
		NotAfter:  now.Add(p.CALifetime),
	})
	if err != nil {
		return Result{}, err
	}
	caFP, _ := caCert.Fingerprint()
	caPub, _ := caBackend.PublicKey()
	if err := s.DB.Create(&store.Key{
		Name: p.CAName, Kind: "ca", Backend: "genesis", Curve: "P256",
		PublicKey: caPub, State: "active", CreatedAt: now.UnixNano(),
	}).Error; err != nil {
		return Result{}, fmt.Errorf("genesis: record CA key: %w", err)
	}
	if err := audit(p.OperatorA, "genesis-ca", p.CAName, fmt.Sprintf(`{"fingerprint":%q}`, caFP)); err != nil {
		return Result{}, err
	}

	// 2. Config-signing root (signs bundles; pinned by Pilot).
	configPub, err := configBackend.PublicKey()
	if err != nil {
		return Result{}, fmt.Errorf("genesis: config-signing public key: %w", err)
	}
	configPubPEM := cert.MarshalSigningPublicKeyToPEM(cert.Curve_P256, configPub)
	configKeyID := keyID(configPub)
	if err := s.DB.Create(&store.Key{
		Name: p.CAName + "-config-signing", Kind: "config-signing", Backend: "genesis", Curve: "P256",
		PublicKey: configPub, State: "active", CreatedAt: now.UnixNano(),
	}).Error; err != nil {
		return Result{}, fmt.Errorf("genesis: record config-signing key: %w", err)
	}
	if err := audit(p.OperatorB, "genesis-config-key", configKeyID, ""); err != nil {
		return Result{}, err
	}

	// 3. First lighthouse certificate (from its own public key — P1).
	pub, _, curve, err := cert.UnmarshalPublicKeyFromPEM(p.LighthousePub)
	if err != nil {
		return Result{}, fmt.Errorf("genesis: parse lighthouse public key: %w", err)
	}
	if curve != cert.Curve_P256 {
		return Result{}, fmt.Errorf("genesis: lighthouse key curve is %s, want P256", curve)
	}
	alloc, err := ipam.NewAllocator(s, ipam.Pool{Prefix: p.Pool})
	if err != nil {
		return Result{}, err
	}
	if err := alloc.AllocateSpecific(ctx, p.LighthouseName, p.LighthouseIP); err != nil {
		return Result{}, fmt.Errorf("genesis: reserve lighthouse IP: %w", err)
	}
	sg, err := signer.New(signer.Config{
		CACertPEM: caPEM, Backend: caBackend,
		Policy: signer.IssuePolicy{AllowedNetwork: p.Pool, MaxLifetime: p.CertLifetime},
		Audit:  func(c context.Context, a, ac, t, d string) error { _, e := s.AppendAudit(c, a, ac, t, d); return e },
	})
	if err != nil {
		return Result{}, err
	}
	nb := now.Add(-5 * time.Minute)
	lhCert, lhPEM, err := sg.Issue(ctx, p.OperatorA, signer.Template{
		Name:      p.LighthouseName,
		Networks:  []netip.Prefix{netip.PrefixFrom(p.LighthouseIP, p.Pool.Bits())},
		Groups:    []string{policy.GroupLighthouse},
		NotBefore: nb,
		NotAfter:  nb.Add(p.CertLifetime),
		PublicKey: pub,
	})
	if err != nil {
		return Result{}, fmt.Errorf("genesis: issue lighthouse cert: %w", err)
	}
	lhFP, _ := lhCert.Fingerprint()

	// 3b. Optional first Core (control-plane) certificate, symmetric with the
	// lighthouse and issued from Core's own public key (P1). Minting it here means the
	// host the firewall baseline routes to (group:control-plane) is created by the same
	// ceremony that establishes the baseline's assumptions — no manual issue-cert gap.
	var corePEM []byte
	var coreFP string
	if len(p.CorePub) > 0 {
		coreName := p.CoreName
		if coreName == "" {
			coreName = "harbor-core"
		}
		if !p.CoreIP.IsValid() {
			return Result{}, fmt.Errorf("genesis: -core-pub provided but core IP is not set")
		}
		cpub, _, ccurve, cerr := cert.UnmarshalPublicKeyFromPEM(p.CorePub)
		if cerr != nil {
			return Result{}, fmt.Errorf("genesis: parse core public key: %w", cerr)
		}
		if ccurve != cert.Curve_P256 {
			return Result{}, fmt.Errorf("genesis: core key curve is %s, want P256", ccurve)
		}
		if err := alloc.AllocateSpecific(ctx, coreName, p.CoreIP); err != nil {
			return Result{}, fmt.Errorf("genesis: reserve core IP: %w", err)
		}
		coreCert, cPEM, cerr := sg.Issue(ctx, p.OperatorA, signer.Template{
			Name:      coreName,
			Networks:  []netip.Prefix{netip.PrefixFrom(p.CoreIP, p.Pool.Bits())},
			Groups:    []string{policy.GroupControlPlane},
			NotBefore: nb,
			NotAfter:  nb.Add(p.CertLifetime),
			PublicKey: cpub,
		})
		if cerr != nil {
			return Result{}, fmt.Errorf("genesis: issue core cert: %w", cerr)
		}
		corePEM = cPEM
		coreFP, _ = coreCert.Fingerprint()
		if err := audit(p.OperatorA, "genesis-core", coreName, fmt.Sprintf(`{"fingerprint":%q,"groups":[%q]}`, coreFP, policy.GroupControlPlane)); err != nil {
			return Result{}, err
		}
	}

	// 4. Manifest + completion record.
	var m manifest
	m.CreatedAt = now.UTC().Format(time.RFC3339)
	m.Operators = []string{p.OperatorA, p.OperatorB}
	m.CAName = p.CAName
	m.CAFingerprint = caFP
	m.ConfigSigningKeyID = configKeyID
	m.Pool = p.Pool.String()
	m.Lighthouse.Name = p.LighthouseName
	m.Lighthouse.OverlayIP = p.LighthouseIP.String()
	m.Lighthouse.PublicAddr = p.LighthouseAddr
	m.Lighthouse.Fingerprint = lhFP
	if corePEM != nil {
		coreName := p.CoreName
		if coreName == "" {
			coreName = "harbor-core"
		}
		m.Core = &manifestNode{Name: coreName, OverlayIP: p.CoreIP.String(), Fingerprint: coreFP}
	}
	manifestJSON, _ := json.MarshalIndent(m, "", "  ")
	if err := audit(p.OperatorB, "genesis-complete", p.CAName,
		fmt.Sprintf(`{"ca":%q,"config_key":%q,"lighthouse":%q}`, caFP, configKeyID, lhFP)); err != nil {
		return Result{}, err
	}

	return Result{
		CACertPEM:             caPEM,
		CAFingerprint:         caFP,
		ConfigSigningPubPEM:   configPubPEM,
		ConfigSigningKeyID:    configKeyID,
		LighthouseCertPEM:     lhPEM,
		LighthouseFingerprint: lhFP,
		LighthouseIP:          p.LighthouseIP,
		CoreCertPEM:           corePEM,
		CoreFingerprint:       coreFP,
		CoreIP:                p.CoreIP,
		ManifestJSON:          manifestJSON,
	}, nil
}

// VerifyControlPlaneCert is the bring-up invariant for the Core node: the host
// running the control plane must present group:control-plane, because the firewall
// baseline (policy §6.3) routes every member's renew/heartbeat to that group. A Core
// without it is silently unreachable. Returns the cert fingerprint on success, or an
// error naming what is wrong — callers (core-api startup) fail fast on it.
func VerifyControlPlaneCert(certPEM []byte) (string, error) {
	c, _, err := cert.UnmarshalCertificateFromPEM(certPEM)
	if err != nil {
		return "", fmt.Errorf("genesis: parse control-plane cert: %w", err)
	}
	for _, g := range c.Groups() {
		if g == policy.GroupControlPlane {
			fp, _ := c.Fingerprint()
			return fp, nil
		}
	}
	return "", fmt.Errorf("genesis: cert %q does not carry group %q — the firewall baseline routes the fleet to group:%s, so this node would be unreachable for renew/heartbeat",
		c.Name(), policy.GroupControlPlane, policy.GroupControlPlane)
}

// keyID is the base64url SHA-256 of a public key — the same identifier the
// protocol spec uses for kid/pubkey_hash.
func keyID(pub []byte) string {
	h := sha256.Sum256(pub)
	return base64.RawURLEncoding.EncodeToString(h[:])
}
