// Package genesis performs the control-plane bootstrap ceremony
// (implementation-plan M3.1): create the two trust roots — the **CA key** (signs
// certs) and the **config-signing key** (signs bundles, protocol spec §3/§6) —
// and issue the first lighthouse certificate, recording every step in the
// hash-chained audit log under two operator identities (a stand-in for real
// cryptographic dual-control, which is 2.11).
//
// P1 is preserved: the lighthouse generates its own key (via `pilot init`) and
// only its public key is handed to genesis; no host private key is centralized.
package genesis

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/netip"
	"time"

	"github.com/jeks313/nebula-control-plane/internal/ipam"
	"github.com/jeks313/nebula-control-plane/internal/netblock"
	"github.com/jeks313/nebula-control-plane/internal/policy"
	"github.com/jeks313/nebula-control-plane/internal/signer"
	"github.com/jeks313/nebula-control-plane/internal/ssoassert"
	"github.com/jeks313/nebula-control-plane/internal/store"
	"github.com/slackhq/nebula/cert"
)

// Params drives a genesis run.
type Params struct {
	OperatorA, OperatorB string // the two ceremony operators (must differ)
	CAName               string
	Pool                 netip.Prefix
	// CentralCIDR is the reserved control-plane block (lighthouse/core + backend
	// headroom), seeded protected at genesis (ADR 0010). Zero -> the pool's first /27.
	CentralCIDR netip.Prefix
	// DefaultCIDR is the bounded fallback block an unbound join method draws from,
	// seeded protected at genesis. Zero -> a /18 at the pool start (operator-sized).
	DefaultCIDR    netip.Prefix
	LighthouseName string
	LighthouseIP   netip.Addr // reserved overlay IP (e.g. 100.64.0.1)
	LighthouseAddr string     // public underlay addr (recorded for the static_host_map)
	LighthousePub  []byte     // the lighthouse's host public key PEM (P1: generated by it)
	// Optional first Core (control-plane) node, symmetric with the lighthouse. When
	// CorePub is set, genesis issues Core's cert in group control-plane and reserves
	// its IP. The firewall baseline (policy §6.3) routes every host to
	// group:control-plane, so a Core node MUST hold that group or heartbeat/renew is
	// unreachable — minting it here keeps the bootstrap self-consistent with the
	// baseline instead of relying on a manual out-of-band issue-cert step.
	CoreName     string
	CoreIP       netip.Addr // reserved overlay IP for Core (e.g. 100.64.0.2)
	CorePub      []byte     // Core's host public key PEM (P1: generated by it); empty = skip
	CALifetime   time.Duration
	CertLifetime time.Duration
	Now          func() time.Time
}

// Result is what a genesis run produced (the operator persists these).
type Result struct {
	CACertPEM             []byte
	CAFingerprint         string
	ConfigSigningPubPEM   []byte
	ConfigSigningKeyID    string
	LighthouseCertPEM     []byte
	LighthouseFingerprint string
	LighthouseIP          netip.Addr
	// Core (control-plane) — populated only when CorePub was provided.
	CoreCertPEM     []byte
	CoreFingerprint string
	CoreIP          netip.Addr
	// SSO assertion-signing keypair (ADR 0004, S6): a DEDICATED ECDSA P-256 keypair,
	// distinct from the CA, minted by the ceremony so the off-mesh enrollment gateway
	// and Core get their halves from the same bootstrap that mints the other roots. The
	// gateway is given the PRIVATE half (Config.SSO.SigningKey via
	// ssoassert.ParsePrivateKeyPEM); Core PINS the PUBLIC half
	// (enrollment.Config.AssertionVerifyKey via ssoassert.ParsePublicKeyPEM). The
	// private half is never stored in the DB (the gateway holds no CA, ADR 0009);
	// genesis only emits the PEMs for the operator to distribute.
	SSOAssertPrivPEM []byte
	SSOAssertPubPEM  []byte
	ManifestJSON     []byte
}

type manifestNode struct {
	Name        string `json:"name"`
	OverlayIP   string `json:"overlay_ip"`
	PublicAddr  string `json:"public_addr,omitempty"`
	Fingerprint string `json:"fingerprint"`
}

type manifest struct {
	CreatedAt          string        `json:"created_at"`
	Operators          []string      `json:"operators"`
	CAName             string        `json:"ca_name"`
	CAFingerprint      string        `json:"ca_fingerprint"`
	ConfigSigningKeyID string        `json:"config_signing_key_id"`
	Pool               string        `json:"pool"`
	Lighthouse         manifestNode  `json:"lighthouse"`
	Core               *manifestNode `json:"core,omitempty"` // present only if Core was issued
}

// Run executes the ceremony against an already-migrated store, using caBackend
// to sign certs and configBackend as the bundle-signing key. Both backends must
// already hold their keys (software: freshly generated by the caller; HSM/KMS:
// pre-provisioned).
func Run(ctx context.Context, s *store.Store, caBackend, configBackend signer.Backend, p Params) (Result, error) {
	if p.Now == nil {
		p.Now = time.Now
	}
	if p.OperatorA == "" || p.OperatorB == "" || p.OperatorA == p.OperatorB {
		return Result{}, fmt.Errorf("genesis: two distinct operators are required")
	}
	now := p.Now()
	audit := func(actor, action, target, details string) error {
		_, err := s.AppendAudit(ctx, actor, action, target, details)
		return err
	}

	// 1. CA root.
	caCert, caPEM, err := signer.SelfSignCA(caBackend, signer.CATemplate{
		Name:      p.CAName,
		Networks:  []netip.Prefix{p.Pool},
		NotBefore: now.Add(-time.Hour),
		NotAfter:  now.Add(p.CALifetime),
	})
	if err != nil {
		return Result{}, err
	}
	caFP, _ := caCert.Fingerprint()
	caPub, _ := caBackend.PublicKey()
	if err := s.DB.Create(&store.Key{
		Name: p.CAName, Kind: "ca", Backend: "genesis", Curve: "P256",
		PublicKey: caPub, State: "active", CreatedAt: now.UnixNano(),
	}).Error; err != nil {
		return Result{}, fmt.Errorf("genesis: record CA key: %w", err)
	}
	if err := audit(p.OperatorA, "genesis-ca", p.CAName, fmt.Sprintf(`{"fingerprint":%q}`, caFP)); err != nil {
		return Result{}, err
	}

	// 2. Config-signing root (signs bundles; pinned by Pilot).
	configPub, err := configBackend.PublicKey()
	if err != nil {
		return Result{}, fmt.Errorf("genesis: config-signing public key: %w", err)
	}
	// The two trust roots MUST be distinct keys (§3/§6 separation: the CA mints certs, the
	// config-signing key signs the bundles Pilot pins). Id-based backends (kms/pkcs11) take
	// operator-supplied identifiers, so the same key id / label in both flags would collapse
	// both roots onto one key that can mint certs AND forge bundles — fail closed. (Software
	// always generates two fresh keys, so this never trips there.)
	if bytes.Equal(caPub, configPub) {
		return Result{}, errors.New("genesis: CA key and config-signing key must be distinct trust roots (the same key was given for both)")
	}
	configPubPEM := cert.MarshalSigningPublicKeyToPEM(cert.Curve_P256, configPub)
	configKeyID := keyID(configPub)
	if err := s.DB.Create(&store.Key{
		Name: p.CAName + "-config-signing", Kind: "config-signing", Backend: "genesis", Curve: "P256",
		PublicKey: configPub, State: "active", CreatedAt: now.UnixNano(),
	}).Error; err != nil {
		return Result{}, fmt.Errorf("genesis: record config-signing key: %w", err)
	}
	if err := audit(p.OperatorB, "genesis-config-key", configKeyID, ""); err != nil {
		return Result{}, err
	}

	// 3. First lighthouse certificate (from its own public key — P1).
	pub, _, curve, err := cert.UnmarshalPublicKeyFromPEM(p.LighthousePub)
	if err != nil {
		return Result{}, fmt.Errorf("genesis: parse lighthouse public key: %w", err)
	}
	if curve != cert.Curve_P256 {
		return Result{}, fmt.Errorf("genesis: lighthouse key curve is %s, want P256", curve)
	}
	alloc, err := ipam.NewAllocator(s, ipam.Pool{Prefix: p.Pool})
	if err != nil {
		return Result{}, err
	}
	// Seed the central + default netblocks (ADR 0010) and wire the registry as the
	// allocator's resolver so central allocations carry netblock_id provenance. The
	// placement math lives in SeedNetblocks, shared with the boot-seed upgrade path.
	nbReg := netblock.New(s.DB, p.Pool, nil, alloc, func(c context.Context, a, ac, t, d string) error {
		_, e := s.AppendAudit(c, a, ac, t, d)
		return e
	})
	if _, _, err := SeedNetblocks(ctx, nbReg, p.Pool, p.CentralCIDR, p.DefaultCIDR, p.OperatorA); err != nil {
		return Result{}, err
	}
	alloc = alloc.WithResolver(nbReg)
	if err := alloc.AllocateSpecific(ctx, p.LighthouseName, p.LighthouseIP, "genesis"); err != nil {
		return Result{}, fmt.Errorf("genesis: reserve lighthouse IP: %w", err)
	}
	sg, err := signer.New(signer.Config{
		CACertPEM: caPEM, Backend: caBackend,
		Policy: signer.IssuePolicy{AllowedNetwork: p.Pool, MaxLifetime: p.CertLifetime},
		Audit:  func(c context.Context, a, ac, t, d string) error { _, e := s.AppendAudit(c, a, ac, t, d); return e },
	})
	if err != nil {
		return Result{}, err
	}
	nb := now.Add(-5 * time.Minute)
	lhCert, lhPEM, err := sg.Issue(ctx, p.OperatorA, signer.Template{
		Name:      p.LighthouseName,
		Networks:  []netip.Prefix{netip.PrefixFrom(p.LighthouseIP, p.Pool.Bits())},
		Groups:    []string{policy.GroupLighthouse},
		NotBefore: nb,
		NotAfter:  nb.Add(p.CertLifetime),
		PublicKey: pub,
	})
	if err != nil {
		return Result{}, fmt.Errorf("genesis: issue lighthouse cert: %w", err)
	}
	lhFP, _ := lhCert.Fingerprint()

	// 3b. Optional first Core (control-plane) certificate, symmetric with the
	// lighthouse and issued from Core's own public key (P1). Minting it here means the
	// host the firewall baseline routes to (group:control-plane) is created by the same
	// ceremony that establishes the baseline's assumptions — no manual issue-cert gap.
	var corePEM []byte
	var coreFP string
	if len(p.CorePub) > 0 {
		coreName := p.CoreName
		if coreName == "" {
			coreName = "harbor-core"
		}
		if !p.CoreIP.IsValid() {
			return Result{}, fmt.Errorf("genesis: -core-pub provided but core IP is not set")
		}
		cpub, _, ccurve, cerr := cert.UnmarshalPublicKeyFromPEM(p.CorePub)
		if cerr != nil {
			return Result{}, fmt.Errorf("genesis: parse core public key: %w", cerr)
		}
		if ccurve != cert.Curve_P256 {
			return Result{}, fmt.Errorf("genesis: core key curve is %s, want P256", ccurve)
		}
		if err := alloc.AllocateSpecific(ctx, coreName, p.CoreIP, "genesis"); err != nil {
			return Result{}, fmt.Errorf("genesis: reserve core IP: %w", err)
		}
		coreCert, cPEM, cerr := sg.Issue(ctx, p.OperatorA, signer.Template{
			Name:      coreName,
			Networks:  []netip.Prefix{netip.PrefixFrom(p.CoreIP, p.Pool.Bits())},
			Groups:    []string{policy.GroupControlPlane},
			NotBefore: nb,
			NotAfter:  nb.Add(p.CertLifetime),
			PublicKey: cpub,
		})
		if cerr != nil {
			return Result{}, fmt.Errorf("genesis: issue core cert: %w", cerr)
		}
		corePEM = cPEM
		coreFP, _ = coreCert.Fingerprint()
		if err := audit(p.OperatorA, "genesis-core", coreName, fmt.Sprintf(`{"fingerprint":%q,"groups":[%q]}`, coreFP, policy.GroupControlPlane)); err != nil {
			return Result{}, err
		}
	}

	// 3c. SSO assertion-signing keypair (ADR 0004, S6). A dedicated ECDSA P-256 key,
	// distinct from the two CA trust roots: the gateway signs short-lived enrollment
	// assertions with the private half, Core pins the public half and re-verifies. The
	// gateway holds NO CA (ADR 0009), so this key cannot mint certs — it only lets the
	// gateway vouch "the IdP said this". Minted here so the same ceremony that
	// establishes the other roots also produces + distributes this one. Only the public
	// half is recorded in the DB key registry (the gateway's private half lives off-mesh
	// on the gateway, never centralized); both PEMs are returned for the operator to
	// distribute. A keygen failure aborts the whole genesis (acceptable — P-256 keygen
	// effectively never fails; SSO being optional means Core fails closed with
	// ErrSSONotConfigured later if the operator never distributes the resulting key).
	ssoPriv, err := ssoassert.GenerateKey()
	if err != nil {
		return Result{}, fmt.Errorf("genesis: generate SSO assertion key: %w", err)
	}
	ssoPrivPEM, err := ssoassert.MarshalPrivateKeyPEM(ssoPriv)
	if err != nil {
		return Result{}, fmt.Errorf("genesis: marshal SSO assertion private key: %w", err)
	}
	ssoPubPEM, err := ssoassert.MarshalPublicKeyPEM(&ssoPriv.PublicKey)
	if err != nil {
		return Result{}, fmt.Errorf("genesis: marshal SSO assertion public key: %w", err)
	}
	ssoKeyID := keyID(ssoPubPEM)
	if err := s.DB.Create(&store.Key{
		Name: p.CAName + "-sso-assertion", Kind: "sso-assertion", Backend: "genesis", Curve: "P256",
		PublicKey: ssoPubPEM, State: "active", CreatedAt: now.UnixNano(),
	}).Error; err != nil {
		return Result{}, fmt.Errorf("genesis: record SSO assertion key: %w", err)
	}
	if err := audit(p.OperatorA, "genesis-sso-assertion-key", ssoKeyID, ""); err != nil {
		return Result{}, err
	}

	// 4. Manifest + completion record.
	var m manifest
	m.CreatedAt = now.UTC().Format(time.RFC3339)
	m.Operators = []string{p.OperatorA, p.OperatorB}
	m.CAName = p.CAName
	m.CAFingerprint = caFP
	m.ConfigSigningKeyID = configKeyID
	m.Pool = p.Pool.String()
	m.Lighthouse.Name = p.LighthouseName
	m.Lighthouse.OverlayIP = p.LighthouseIP.String()
	m.Lighthouse.PublicAddr = p.LighthouseAddr
	m.Lighthouse.Fingerprint = lhFP
	if corePEM != nil {
		coreName := p.CoreName
		if coreName == "" {
			coreName = "harbor-core"
		}
		m.Core = &manifestNode{Name: coreName, OverlayIP: p.CoreIP.String(), Fingerprint: coreFP}
	}
	manifestJSON, _ := json.MarshalIndent(m, "", "  ")
	if err := audit(p.OperatorB, "genesis-complete", p.CAName,
		fmt.Sprintf(`{"ca":%q,"config_key":%q,"lighthouse":%q}`, caFP, configKeyID, lhFP)); err != nil {
		return Result{}, err
	}

	return Result{
		CACertPEM:             caPEM,
		CAFingerprint:         caFP,
		ConfigSigningPubPEM:   configPubPEM,
		ConfigSigningKeyID:    configKeyID,
		LighthouseCertPEM:     lhPEM,
		LighthouseFingerprint: lhFP,
		LighthouseIP:          p.LighthouseIP,
		CoreCertPEM:           corePEM,
		CoreFingerprint:       coreFP,
		CoreIP:                p.CoreIP,
		SSOAssertPrivPEM:      ssoPrivPEM,
		SSOAssertPubPEM:       ssoPubPEM,
		ManifestJSON:          manifestJSON,
	}, nil
}

// VerifyControlPlaneCert is the bring-up invariant for the Core node: the host
// running the control plane must present group:control-plane, because the firewall
// baseline (policy §6.3) routes every member's renew/heartbeat to that group. A Core
// without it is silently unreachable. Returns the cert fingerprint on success, or an
// error naming what is wrong — callers (core-api startup) fail fast on it.
func VerifyControlPlaneCert(certPEM []byte) (string, error) {
	c, _, err := cert.UnmarshalCertificateFromPEM(certPEM)
	if err != nil {
		return "", fmt.Errorf("genesis: parse control-plane cert: %w", err)
	}
	for _, g := range c.Groups() {
		if g == policy.GroupControlPlane {
			fp, _ := c.Fingerprint()
			return fp, nil
		}
	}
	return "", fmt.Errorf("genesis: cert %q does not carry group %q — the firewall baseline routes the fleet to group:%s, so this node would be unreachable for renew/heartbeat",
		c.Name(), policy.GroupControlPlane, policy.GroupControlPlane)
}

// SeedNetblocks seeds the two protected genesis netblocks — 'central' (the
// control-plane reserved /27) and 'default' (the bounded fallback) — into reg,
// resolving each CIDR from the optional operator overrides or the standard
// placement defaults (the same math genesis uses; see CentralBlock/defaultBlock).
// It is the single seeding chokepoint shared by the genesis ceremony (genesis.Run)
// and the harbor boot-seed upgrade path (cmd/harbor/serve.go), so the CIDR math is
// never duplicated.
//
// Seed itself is idempotent on the name: a row that already exists is returned
// unchanged, and a concurrent insert that loses the UNIQUE(name) race is folded
// back to the existing row — so two services boot-seeding at once is safe and a
// re-genesis is a no-op. Returns the central and default rows.
func SeedNetblocks(ctx context.Context, reg *netblock.Registry, pool, centralOverride, defaultOverride netip.Prefix, actor string) (central, def netblock.Netblock, err error) {
	centralCIDR := centralOverride
	if !centralCIDR.IsValid() {
		centralCIDR = CentralBlock(pool)
	}
	defaultCIDR := defaultOverride
	if !defaultCIDR.IsValid() {
		defaultCIDR = defaultBlock(pool)
	}
	central, err = reg.Seed(ctx, netblock.NameCentral, centralCIDR, netblock.KindReserved,
		"control-plane reserved space (lighthouse, core, backends)", actor)
	if err != nil {
		return netblock.Netblock{}, netblock.Netblock{}, fmt.Errorf("genesis: seed central netblock: %w", err)
	}
	def, err = reg.Seed(ctx, netblock.NameDefault, defaultCIDR, netblock.KindDefault,
		"bounded fallback for unbound join methods", actor)
	if err != nil {
		return netblock.Netblock{}, netblock.Netblock{}, fmt.Errorf("genesis: seed default netblock: %w", err)
	}
	return central, def, nil
}

// BootSeedNetblocks is the existing-mesh upgrade path (IPAM-DECISIONS D22): an
// already-genesis'd mesh that upgrades to the IPAM build runs migrations
// 000022/000023 (creating an empty netblocks table) but never ran genesis again, so
// the 'default' netblock the allocator resolves unbound enrollments to is missing —
// every new enrollment would break. Harbor's long-running services (core-api,
// admin-api) call this at startup, AFTER migrations, to seed central+default the
// same way genesis would.
//
// It only seeds when the table is EMPTY, so it never disturbs a genesis'd or
// operator-curated set (a count check; a populated table is a no-op returning
// false). It is race/duplicate-tolerant: core-api and admin-api may both boot and
// both attempt it, so a concurrent insert that loses the UNIQUE(name) race is
// swallowed by Seed (it folds the duplicate back to the existing row) — seeding
// twice is a no-op, not a crash. Returns whether it actually seeded.
//
// Logs an info line when it seeds (so the upgrade is visible in operator logs). A
// caller that wants the warn-but-don't-abort posture should log the returned error
// rather than fatal on it: a missing default surfaces as enrollment errors that are
// already audited + metered, so a transient seed failure is recoverable on the next
// boot and must not take the control plane down.
func BootSeedNetblocks(ctx context.Context, reg *netblock.Registry, pool, centralOverride, defaultOverride netip.Prefix, actor string, log *slog.Logger) (seeded bool, err error) {
	if log == nil {
		log = slog.Default()
	}
	n, err := reg.Count(ctx)
	if err != nil {
		return false, fmt.Errorf("genesis: boot-seed count netblocks: %w", err)
	}
	if n > 0 {
		return false, nil // genesis'd or operator-curated — leave it alone
	}
	central, def, err := SeedNetblocks(ctx, reg, pool, centralOverride, defaultOverride, actor)
	if err != nil {
		return false, err
	}
	log.Info("netblock: boot-seeded central + default (existing-mesh upgrade — netblocks table was empty)",
		"central", central.CIDR, "default", def.CIDR, "pool", pool.String())
	return true, nil
}

// CentralBlock is the control-plane reserved CIDR when the operator does not supply
// -central-cidr: the pool's first /27 (lighthouse + core + backend headroom). It is
// the single source of truth for the central reserved block — genesis/SeedNetblocks
// seed THIS CIDR, and the device reaper computes its never-reap central guard from it
// (cmd/harbor serve.go) so the guard is deterministic and always on regardless of
// registry/boot-seed state (REAPER-DECISIONS R10).
func CentralBlock(pool netip.Prefix) netip.Prefix {
	return netip.PrefixFrom(pool.Masked().Addr(), 27).Masked()
}

// defaultBlock picks a sensible bounded 'default' CIDR when the operator does not
// supply -default-cidr: a /18 (or the whole pool, if the pool is coarser than /18)
// placed at the first aligned slot clear of central (the first /27). It uses the
// same growth-aware placement the IPAM UI uses, treating central as a carve, so the
// default lands away from the control-plane block (e.g. 10.44.64.0/18, not the pool
// start). Operators size this explicitly in production; this is a workable default.
func defaultBlock(pool netip.Prefix) netip.Prefix {
	pool = pool.Masked()
	want := 18
	if pool.Bits() > want {
		want = pool.Bits() // pool coarser than /18 -> the whole pool
	}
	central := CentralBlock(pool)
	p, err := netblock.Suggest(want, pool, nil, []netip.Prefix{central})
	if err != nil {
		// Fall back to the slot immediately after central, aligned to /want.
		return netip.PrefixFrom(pool.Addr(), want).Masked()
	}
	return p
}

// keyID is the base64url SHA-256 of a public key — the same identifier the
// protocol spec uses for kid/pubkey_hash.
func keyID(pub []byte) string {
	h := sha256.Sum256(pub)
	return base64.RawURLEncoding.EncodeToString(h[:])
}
